apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Release.Name }}
data:
  SQL_PASSWORD: {{ required "Database password required" .Values.bootzooka.sql.password | b64enc | quote }}
  SMTP_PASSWORD: {{ required "SMTP password required" .Values.bootzooka.smtp.password | b64enc | quote }}
  